### ISSUE TITLE
Having problems with cufon.

### ISSUE THREAD

**Issue by Eliteoomph** [norcross/gf-tooltips#2]
As you can see I have a tooltip about halfway down but the text is not displaying.  I am thinking it might be a problem with cufon but not sure...

**Comment by norcross** [comment]
you didn't provide a URL, so I'm not sure where this is occuring. That being said, Cufon very well may be an issue because Cufon is (in my opinion) complete garbage.

**Comment by Eliteoomph** [comment]
Yeah that would probably help

http://bigcitymarketing.net/500-web-design-package/

**Comment by norcross** [comment]
ok. looking at the URL, I don't see where you are using the tooltips (I see the 'manual' distinction, but no actual tooltip data). Have you entered any content into the description field to trigger the tooltip?

Also, I would really encourage you to get rid of Cufon. it's just a nasty method of font usage, and outdated. Here's the font itself: http://fontfabric.com/hero-free-font/ and here's how to make your own font-face kit http://www.fontsquirrel.com/fontface/generator

**Comment by Eliteoomph** [comment]
Yes I have text in the description… And if you highlight the tooltip area you will see it is highlighting something…

**Comment by norcross** [comment]
ah, I see the tooltip now. Yes, cufon is causing the problem, as it breaks apart text into multiple spans with extra markup, which breaks the functionality. if you have something in your theme that allows you to disable cufon on a specific class, use that. otherwise it's not something I can fix on the plugin side.

one thing I noticed: your entire form is somehow wrapped in an `H3` tag. this is causing the cufon to be applied to the entire thing. try fixing that and it may go away, but it also may remove styling you want.

**Comment by Eliteoomph** [comment]
I’ll try that, thanks for your help.  Good job on the plugin btw.

**Comment by norcross** [comment]
no problem. I'm gonna make a few tweaks / options to it before I release it 'officially'.
